name: PointsOfInterest
main: crussell52.poi.PointsOfInterest
version: 1.0.0

permissions:
    poi.action.*:
        description: Gives access to all actions under the poi command
        children:
            poi.action.add: true
            poi.action.config.reload: true
            poi.action.remove: true
            poi.action.remove.others: true
            poi.action.view: true
            poi.action.teleport: true
    poi.action.add:
        description: Allows you to add POIs
        default: op
    poi.action.config.reload:
        description: Allows you to reload the configuration from the file
        default: op
    poi.action.remove:
        description: Allows you to remove POIs
        default: op
        children:
            poi.action.view: true
    poi.action.remove.others:
        description: Allows you to remove POIs that belong to other players as well as your own.
        default: op
        children:
            poi.action.remove: true
    poi.action.view:
        description: Allows you to search for and view POIs.
        default: true
    poi.action.teleport:
        description: Allows you to teleport to POIs.
        default: op
        children:
          poi.action.view: true

commands:
    poi:
       description: Show your friends what's interesting in the world!
       usage: |
           Use "/poi help" for guidance.
